server:
  port: 8080
logging:
  level:
    org.springframework.security: DEBUG
    
# Set here configurations for the database connection
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.30.158.146:3306/harsha 
    username: harsha		
    password: harsha
    continueOnError: true
    initialize: false
    initialSize: 0
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 5000
    minIdle: 0
